### PR TITLE
html boilerplate

### PR DESCRIPTION
**Pull request by fimoefive**
htmlboiler plate and script tags. Also the starter code for all the dataProvider.js files"

### CODE REVIEW

**Review by ZachRoark — APPROVED** [review]
👍

**Comment by jenniferstarkey** [comment]
Looking good!

**Review by jenniferstarkey — APPROVED** [review]
Dope

**Review by danicrosby — COMMENTED** [review]
LGTM

**Review by danicrosby — APPROVED** [review]

**Pull request merged**
